##### One Host and a Mysql server with the Docker ####

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    vb.cpus = 1
  end
    config.vm.define "router-1" do |router1|
    router1.vm.box = "bento/ubuntu-16.04"
    router1.vm.hostname = "router-1"
    router1.vm.network "private_network", ip: "192.168.10.2", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-1", auto_config: true
    router1.vm.network "private_network", ip: "192.168.10.3", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-2", auto_config: true
	router1.vm.network "private_network", ip: "192.168.10.4", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-3", auto_config: true
    router1.vm.provision "shell", run: "always", inline: <<-SHELL
	echo " Quagga Router-2 start installing"
	#sudo sysctl -w net.ipv4.ip_forward=1
	sudo apt-get update
	sudo apt-get install quagga quagga-doc traceroute
	sudo cp /usr/share/doc/quagga/examples/zebra.conf.sample /etc/quagga/zebra.conf
	sudo cp /usr/share/doc/quagga/examples/ospfd.conf.sample /etc/quagga/ospfd.conf
	sudo chown quagga.quaggavty /etc/quagga/*.conf
	sudo /etc/init.d/quagga start
	sudo sed -i s'/zebra=no/zebra=yes/' /etc/quagga/daemons
	sudo sed -i s'/ospfd=no/ospfd=yes/' /etc/quagga/daemons
	sudo echo 'VTYSH_PAGER=more' >>/etc/environment
	sudo echo 'export VTYSH_PAGER=more' >>/etc/bash.bashrc
	sudo /etc/init.d/quagga restart
	echo "Routing Protocol ospf Configuration Started"
	sudo vtysh -c '
	configure terminal
	router ospf
	network 192.168.10.0/24 area 0.0.0.0
	interface eth1
	ip address 192.168.10.2/24
	exit
	interface eth2
	ip address 192.168.10.3/24
	exit
	interface eth3
	ip address 192.168.10.4/24
	do write
	exit
	exit
	ip forwarding
	exit'
	echo "Configuration END"
	echo "Router--1 is ready to Use"	
	SHELL
	router1.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    end
    end
    config.vm.define "host-a" do |hosta|
    hosta.vm.box = "bento/ubuntu-16.04"
    hosta.vm.hostname = "host-a"
    hosta.vm.network "private_network", ip: "192.168.10.10", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-1", auto_config: true
    hosta.vm.provision "shell", run: "always", inline: <<-SHELL
	echo "Static Routig configuration Started for Host--A"
	sudo sysctl -w net.ipv4.ip_forward=1
	sudo route add -net 192.168.10.0 netmask 255.255.255.0 gw 192.168.10.2 dev eth1
	echo "Configuration END"
	echo "Host--A is ready to Use"	
	SHELL
	hosta.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
    end
 # Configure web server machine
     config.vm.define "web1" do |web1|
         web1.vm.box = "bento/ubuntu-16.04"
		 web1.vm.hostname = "web-1"
         web1.vm.network "private_network", ip: "192.168.10.11", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-2", auto_config: true
         web1.vm.provision "shell", run: "always", inline: <<-SHELL
	     echo "Static Routig configuration Started for web-1"
	     sudo sysctl -w net.ipv4.ip_forward=1
	     sudo route add -net 192.168.10.0 netmask 255.255.255.0 gw 192.168.10.3 dev eth1
         echo "Configuration END"
	     #echo "web-1 is ready to Use"	
	     SHELL
		 web1.vm.provision "docker" do |doc|
		 doc.pull_images "nginx"
		 doc.pull_images "php"
		 doc.run "nginx"
		 doc.run "php"
         web1.vm.provider "virtualbox" do |vb|
     vb.memory = 1024
    end
    end
    end
    # Configure database server machine
     config.vm.define "db1" do |db1|
         db1.vm.box = "bento/ubuntu-16.04"
		 db1.vm.hostname = "db-1"
         db1.vm.network "private_network", ip: "192.168.10.12", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-3", auto_config: true
         db1.vm.provision "shell", run: "always", inline: <<-SHELL
	     echo "Static Routig configuration Started for db-1"
	     sudo sysctl -w net.ipv4.ip_forward=1
	     sudo route add -net 192.168.10.0 netmask 255.255.255.0 gw 192.168.10.4 dev eth1
         echo "Configuration END"
	     #echo "Host--B is ready to Use"	
	     SHELL
		 db1.vm.provision "docker" do |doc|
	     doc.pull_images "mysql"
		 doc.run "mysql"
		 db1.vm.provider "virtualbox" do |vb|
     vb.memory = 1024
    end
	end	 	 
    end
    end




