# -*- mode: ruby -*- 
# vi: set ft=ruby :

#All Vagrant configuration is done below. The 2 in Vagrant.configure
#configures the configuration version we support older styles for
#backwards compatibility. Please don't change it unless you know what
#you're doing.
Vagrant.configure("2") do |config|
config.vm.box_check_update = true
config.vm.provider "virtualbox" do |vb|
vb.customize ["modifyvm", :id, "--usb", "on"]
vb.customize ["modifyvm", :id, "--usbehci", "off"]
vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
vb.cpus = 1
end
config.vm.define "routerjack" do |routerjack|
routerjack.vm.box = "bento/ubuntu-16.04"
routerjack.vm.hostname = "routerjack"
routerjack.vm.network "private_network", virtualbox__intnet: "broadcast_router-south-2", auto_config: false
routerjack.vm.network "private_network", virtualbox__intnet: "broadcast_router-inter-2", auto_config: false
routerjack.vm.network "private_network", virtualbox__intnet: "broadcast_router-inter-1", auto_config: false
routerjack.vm.provision "shell", inline: <<-SHELL
echo " Quagga routerjack start installing"
#sudo sysctl -w net.ipv4.ip_forward=1
sudo apt-get update
sudo apt-get install quagga quagga-doc traceroute
sudo cp /usr/share/doc/quagga/examples/zebra.conf.sample /etc/quagga/zebra.conf
sudo cp /usr/share/doc/quagga/examples/ospfd.conf.sample /etc/quagga/ospfd.conf
sudo chown quagga.quaggavty /etc/quagga/*.conf
sudo /etc/init.d/quagga start
sudo sed -i s'/zebra=no/zebra=yes/' /etc/quagga/daemons
sudo sed -i s'/ospfd=no/ospfd=yes/' /etc/quagga/daemons
sudo echo 'VTYSH_PAGER=more' >>/etc/environment
sudo echo 'export VTYSH_PAGER=more' >>/etc/bash.bashrc
sudo /etc/init.d/quagga restart
echo "Routing Protocol ospf Configuration Started"
sudo vtysh -c '
configure terminal
router ospf
network 192.168.1.0/24 area 0.0.0.0
network 192.168.100.0/24 area 0.0.0.0
network 192.168.101.0/24 area 0.0.0.0
exit
interface eth1
ip address 192.168.1.254/24
exit
interface eth2
ip address 192.168.100.1/24
exit
interface eth3
ip address 192.168.101.2/24
do write
exit
exit
ip forwarding
exit'
echo "Configuration END"
echo "routerjack is ready to Use"
SHELL
# routerjack.vm.provision "shell", path: "common.sh"
routerjack.vm.provider "virtualbox" do |vb|
vb.memory = 1024
end
end
config.vm.define "routersteve" do |routersteve|
routersteve.vm.box = "bento/ubuntu-16.04"
routersteve.vm.hostname = "routersteve"
routersteve.vm.network "private_network", virtualbox__intnet: "broadcast_router-south-3", auto_config: false
routersteve.vm.network "private_network", virtualbox__intnet: "broadcast_router-inter-3", auto_config: false
routersteve.vm.network "private_network", virtualbox__intnet: "broadcast_router-inter-2", auto_config: false
routersteve.vm.provision "shell", inline: <<-SHELL
echo " Quagga routersteve start installing"
#sudo sysctl -w net.ipv4.ip_forward=1
sudo apt-get update
sudo apt-get install quagga quagga-doc traceroute
sudo cp /usr/share/doc/quagga/examples/zebra.conf.sample /etc/quagga/zebra.conf
sudo cp /usr/share/doc/quagga/examples/ospfd.conf.sample /etc/quagga/ospfd.conf
sudo chown quagga.quaggavty /etc/quagga/*.conf
sudo /etc/init.d/quagga start
sudo sed -i s'/zebra=no/zebra=yes/' /etc/quagga/daemons
sudo sed -i s'/ospfd=no/ospfd=yes/' /etc/quagga/daemons
sudo echo 'VTYSH_PAGER=more' >>/etc/environment
sudo echo 'export VTYSH_PAGER=more' >>/etc/bash.bashrc
sudo /etc/init.d/quagga restart
echo "Routing Protocol ospf Configuration Started"
sudo vtysh -c '
configure terminal
router ospf
network 192.168.2.0/24 area 0.0.0.0
network 192.168.100.0/24 area 0.0.0.0
network 192.168.102.0/24 area 0.0.0.0
exit
interface eth1
ip address 192.168.2.254/24
exit
interface eth2
ip address 192.168.100.2/24
exit
interface eth3
ip address 192.168.102.2/24
do write
exit
exit
ip forwarding
exit'
echo "Configuration END"
echo "routersteve is ready to Use"
SHELL
# routersteve.vm.provision "shell", path: "common.sh"
routersteve.vm.provider "virtualbox" do |vb|
vb.memory = 1024
end
end
config.vm.define "ruoterjhon" do |ruoterjhon|
ruoterjhon.vm.box = "bento/ubuntu-16.04"
ruoterjhon.vm.hostname = "ruoterjhon"
ruoterjhon.vm.provision "shell", inline: <<-SHELL
echo " Quagga ruoterjhon start installing"
#sudo sysctl -w net.ipv4.ip_forward=1
sudo apt-get update
sudo apt-get install quagga quagga-doc traceroute
sudo cp /usr/share/doc/quagga/examples/zebra.conf.sample /etc/quagga/zebra.conf
sudo cp /usr/share/doc/quagga/examples/ospfd.conf.sample /etc/quagga/ospfd.conf
sudo chown quagga.quaggavty /etc/quagga/*.conf
sudo /etc/init.d/quagga start
sudo sed -i s'/zebra=no/zebra=yes/' /etc/quagga/daemons
sudo sed -i s'/ospfd=no/ospfd=yes/' /etc/quagga/daemons
sudo echo 'VTYSH_PAGER=more' >>/etc/environment
sudo echo 'export VTYSH_PAGER=more' >>/etc/bash.bashrc
sudo /etc/init.d/quagga restart
echo "Routing Protocol ospf Configuration Started"
sudo vtysh -c '
configure terminal
router ospf
network 192.168.3.0/24 area 0.0.0.0
network 192.168.101.0/24 area 0.0.0.0
network 192.168.102.0/24 area 0.0.0.0
exit
interface eth1
ip address 192.168.3.254/24
exit
interface eth2
ip address 192.168.101.1/24
exit
interface eth3
ip address 192.168.102.1/24
do write
exit
exit
ip forwarding
exit'
echo "Configuration END"
echo "ruoterjhon is ready to Use"
SHELL
# ruoterjhon.vm.provision "shell", path: "common.sh"
ruoterjhon.vm.provider "virtualbox" do |vb|
vb.memory = 1024
end
end
config.vm.define "hostbanana" do |hostbanana|
hostbanana.vm.box = "bento/ubuntu-16.04"
hostbanana.vm.hostname = "hostbanana"
hostbanana.vm.network "private_network", ip: "192.168.1.1", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-2", auto_config: true
hostbanana.vm.provision "shell", run: "always", inline: <<-SHELL
echo "Static Routig configuration Started for hostbanana"
sudo sysctl -w net.ipv4.ip_forward=1
sudo route add -net 192.168.1.0 netmask 255.255.255.0 gw 192.168.1.254 dev eth1
echo "Configuration END"
echo "hostbanana is ready to Use"
SHELL
hostbanana.vm.provider "virtualbox" do |vb|
vb.memory = 1024
end
end
config.vm.define "hostmela" do |hostmela|
hostmela.vm.box = "bento/ubuntu-16.04"
hostmela.vm.hostname = "hostmela"
hostmela.vm.network "private_network", ip: "192.168.2.1", netmask: "255.255.255.0", virtualbox__intnet: "broadcast_router-south-3", auto_config: true
hostmela.vm.provision "shell", run: "always", inline: <<-SHELL
echo "Static Routig configuration Started for hostmela"
sudo sysctl -w net.ipv4.ip_forward=1
sudo route add -net 192.168.2.0 netmask 255.255.255.0 gw 192.168.2.254 dev eth1
echo "Configuration END"
echo "hostmela is ready to Use"
SHELL
hostmela.vm.provider "virtualbox" do |vb|
vb.memory = 1024
end
end
config.vm.define "hostpera" do |hostpera|
hostpera.vm.box = "bento/ubuntu-16.04"
hostpera.vm.hostname = "hostpera"
hostpera.vm.provision "shell", run: "always", inline: <<-SHELL
echo "Static Routig configuration Started for hostpera"
sudo sysctl -w net.ipv4.ip_forward=1
sudo route add -net 192.168.3.0 netmask 255.255.255.0 gw 192.168.3.254 dev eth1
echo "Configuration END"
echo "hostpera is ready to Use"
SHELL
hostpera.vm.provider "virtualbox" do |vb|
vb.memory = 1024
end
end
end
